# Those hparams which are in a list 
# apply differently to each ntwrk
# Should match with NUM_AGENTS_PER_TYPE

"LR": [5e-5]
"NUM_ENVS": 512
"NUM_STEPS": 512
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 16
"GAMMA": [0.999]
"GAE_LAMBDA": [0.99]
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": [False]
"ENT_COEF": [0.01]
"VF_COEF": [0.001]
"MAX_GRAD_NORM": [0.5]
"ACTIVATION": ["relu"]
"ENV_NAME": "JAXMARL-Lob-v0"
"NUM_AGENTS_PER_TYPE": [1]
"SEED": 0
# "ENV_KWARGS": 
#     "LIST_OF_AGENTS_CONFIGS: []
#     "NUM_AGENTS_PER_TYPE": True
# #   "attack_mode": "closest"
"ANNEAL_LR": [True]

# WandB Params
"ENTITY": "oxford-lob"
"PROJECT": "DebugConfig"
"WANDB_MODE" : "online"

# High-Level Params
"CALC_EVAL" : True
"Calculate Baseline" : True



