# Those hparams which are in a list 
# apply differently to each ntwrk
# Should match with NUM_AGENTS_PER_TYPE

"NUM_ENVS": 4096
"NUM_STEPS": 128
"TINY_RUN": False

# "NUM_ENVS": 8
# "NUM_STEPS": 64
# "TINY_RUN": True


"ENV_NAME": "JAXMARL-Lob-v0"
"NUM_AGENTS_PER_TYPE": [1,1]
"SEED": 34
"N_DEVICES": 1
"FIXED_ACTIONS" : [[0],[0]]

# WandB Params
"ENTITY": "oxford-lob"
"PROJECT": "Baseline_JAXMARL"
"WANDB_MODE" : "disabled"

# High-Level Params
"CALC_EVAL" : False
"EvalTimePeriod" : "2024_Eval" #"2024"


#Network params that must be manually matched with the config used in the original training
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
#Training params which are irellevant for the eval.
"ANNEAL_LR": True
"LR": 20
"MAX_GRAD_NORM" : 25


"RESTORE_PROJECT" : "v4_2Player_various_act_reward_spaces"
"RESTORE_RUN" : "fluent-sweep-3"



"AGENT_CONFIGS" : {"MarketMaking" :{"inv_penalty": "quadratic",
                                    "skew_multiplier": 10,
                                    "action_space":"fixed_quants", #"spread_skew",,"fixed_quants"simple
                                    "reward_space" : "spooner", # "spooner"buy_sell_pnl
                                  },
                  "Execution" : {"reward_lambda": 0.0,
                                "fixed_quant_value": 10, #20 on fixed quants
                                "action_space": "fixed_quants_complex", #fixed_quants,fixed_quants_complex
                                 "task_size": 600,
                                "doom_price_penalty": 0.1,}
                }
"BASELINE_CONFIGS" : {"MarketMaking" :{"action_space":"AvSt", #"spread_skew",,"fixed_quants"simple
                                    },
                  "Execution" : {"action_space": "twap"}
                }




      #   """Action function for the fixed Quant Action space
      #   Pick for a ladder of quant execution options
      #   Always send 4 messages
      #   0 = No trade
      #   1=      # FT
      #   2=     # M
      #   3=    # NT
      #   4=    # PP
      #   5=    # FT*2 quant
      #   6=    # M*2 quant
      #   7=    # NT*2 quant
      #   8=    # PP*2 quant
      #   9=    # FT*5 quant
      #   10=   # M*5 quant
      #   11=   # NT*5 quant
      #   12=   # PP*5 quant

        
      #  """


        # Mapping:
        # 0: tight spread, bid skew
        # 1: tight spread, neutral 
        # 2: tight spread, ask skew
        # 3: wide spread, bid skew
        # 4: wide spread, neutral
        # 5: wide spread, ask skew
        # '''